packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
  - "@swc/core"

overrides:
  "@expo/dom-webview": "56.0.5"
  "@types/react": "19.2.17"
  "@types/react-dom": "19.2.3"

peerDependencyRules:
  ignoreMissing:
    - "@expo/dom-webview"
  allowAny:
    - "@expo/dom-webview"
